server:
  port: 8080
  name: e-shop
spring:
  datasource:
    url:
    username: 
    password:
jwt:
  secret:
    key:
  expiration: 3600

aws:
  accessKey:
  secretKey:
  region: eu-south-2
  bucketName: