spring:
  datasource:
    url: jdbc:mysql://localhost/e-shop
    username: root
    password: root
jwt:
  secret:
    key: 97
  expiration: 3600

aws:
  accessKey: AK
  secretKey: 60
  region: eu-south-2
  bucketName: test